In [2]:
from helper import load_titanic

df = load_titanic()
df.sort_values('Fare', ascending=False)[['Name', 'Fare']].head(3)

                                   Name      Fare
258                    Ward, Miss. Anna  512.3292
737              Lesurer, Mr. Gustave J  512.3292
679  Cardeza, Mr. Thomas Drake Martinez  512.3292

In [4]:
df.sort_values(['Pclass', 'Age'], ascending=[True, False])[['Name', 'Pclass', 'Age']]

                                         Name  Pclass   Age
630      Barkworth, Mr. Algernon Henry Wilson       1  80.0
96                  Goldschmidt, Mr. George B       1  71.0
493                   Artagaveytia, Mr. Ramon       1  71.0
745              Crosby, Capt. Edward Gifford       1  70.0
54             Ostby, Mr. Engelhart Cornelius       1  65.0
..                                        ...     ...   ...
859                          Razi, Mr. Raihed       3   NaN
863         Sage, Miss. Dorothy Edith "Dolly"       3   NaN
868               van Melkebeke, Mr. Philemon       3   NaN
878                        Laleff, Mr. Kristo       3   NaN
888  Johnston, Miss. Catherine Helen "Carrie"       3   NaN

[891 rows x 3 columns]

In [5]:
df.groupby('Sex')['Survived'].mean().round(2)

Sex
female    0.74
male      0.19
Name: Survived, dtype: float64

In [7]:
df.groupby('Pclass')['Fare'].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [11]:
df['ClassAvgFare'] = df.groupby('Pclass')['Fare'].transform('mean')
# 여러분이 할것: FareRatio => Fare / ClassAvgFare
df['FareRatio'] = df['Fare'] / df['ClassAvgFare']
df[['Name', 'Pclass', 'Fare', 'ClassAvgFare', 'FareRatio']]

                                                  Name  ...  FareRatio
0                              Braund, Mr. Owen Harris  ...   0.530143
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  ...   0.847051
2                               Heikkinen, Miss. Laina  ...   0.579501
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  ...   0.630981
4                             Allen, Mr. William Henry  ...   0.588642
..                                                 ...  ...        ...
886                              Montvila, Rev. Juozas  ...   0.629169
887                       Graham, Miss. Margaret Edith  ...   0.356486
888           Johnston, Miss. Catherine Helen "Carrie"  ...   1.714739
889                              Behr, Mr. Karl Howell  ...   0.356486
890                                Dooley, Mr. Patrick  ...   0.566705

[891 rows x 5 columns]