In [9]:
import pandas as pd
from helper import load_bike_raw

df = load_bike_raw()
df['date'].dtype
df['date'] = pd.to_datetime(df['date'], format='%Y-%m-%d')
print(df['date'].dtype)

datetime64[us]

In [17]:
df['date'].dt.year.head(2).tolist()
df['date'].dt.month.head(2).tolist()
df['date'].dt.dayofweek.head(2).tolist()
df['date'].dt.day_name().head(2).tolist()

['Friday', 'Friday']

In [26]:
df['datetime'] = df['date'] + pd.to_timedelta(df['hour'], unit='h')
df[['date', 'hour', 'datetime', 'rented']]

           date  hour            datetime  rented
0    2017-12-01     0 2017-12-01 00:00:00     254
1    2017-12-01     1 2017-12-01 01:00:00     204
2    2017-12-01     2 2017-12-01 02:00:00     173
3    2017-12-01     3 2017-12-01 03:00:00     107
4    2017-12-01     4 2017-12-01 04:00:00      78
...         ...   ...                 ...     ...
8755 2018-11-30    19 2018-11-30 19:00:00    1003
8756 2018-11-30    20 2018-11-30 20:00:00     764
8757 2018-11-30    21 2018-11-30 21:00:00     694
8758 2018-11-30    22 2018-11-30 22:00:00     712
8759 2018-11-30    23 2018-11-30 23:00:00     584

[8760 rows x 4 columns]

In [31]:
df.groupby(df['date'].dt.month)['rented'].sum()
df.groupby('hour')['rented'].mean().sort_values(ascending=False)
# hour <- 시간대별 평균 rented 수 계산하는데.. -> 정렬  내리차순

hour
18    1502.926027
19    1195.147945
17    1138.509589
20    1068.964384
21    1031.449315
8     1015.701370
16     930.621918
22     922.797260
15     829.186301
14     758.824658
13     733.246575
12     699.441096
23     671.126027
9      645.983562
7      606.005479
11     600.852055
0      541.460274
10     527.821918
1      426.183562
2      301.630137
6      287.564384
3      203.331507
5      139.082192
4      132.591781
Name: rented, dtype: float64

In [33]:
df['is_weekend'] = df['date'].dt.dayofweek >= 5
df.groupby('is_weekend')['rented'].mean()

is_weekend
False    719.448914
True     667.342147
Name: rented, dtype: float64

# 55 분까지 휴식

# 문제 1
- Spring, Autumn (봄, 가을) 시간대만 뽑고
- 기온 20 ~ 25도 인 시간대만 뽑아서
- 시간대별 총 rented 총 갯수
- hour0: 16813

# 문제 2
- 대여수가 가장 많은 상위 5개 rows 뽑는다 -> 눈으로 공통점을 찾기
- nlargest 함수 <- 구글 검색

- 4818

In [43]:
season_mask = df['season'].isin(['Spring', 'Autumn'])
temperature_mask = df['temp'].between(20, 25)

df[season_mask & temperature_mask].groupby('hour')[['rented']].sum()
print()

In [44]:
df.nlargest(5, 'rented')

,date,rented,hour,temp,humidity,wind,visibility,dew_point,solar,rainfall,snowfall,season,holiday,functioning,datetime,is_weekend
4818,2018-06-19,3556,18,24.1,57,2.9,1301,15.0,0.56,0.0,0.0,Summer,No Holiday,Yes,2018-06-19 18:00:00,False
4866,2018-06-21,3418,18,27.8,43,3.0,1933,14.0,1.35,0.0,0.0,Summer,No Holiday,Yes,2018-06-21 18:00:00,False
4650,2018-06-12,3404,18,24.9,53,3.6,2000,14.6,1.28,0.0,0.0,Summer,No Holiday,Yes,2018-06-12 18:00:00,False
4842,2018-06-20,3384,18,27.0,55,3.1,1246,17.1,1.26,0.0,0.0,Summer,No Holiday,Yes,2018-06-20 18:00:00,False
4458,2018-06-04,3380,18,24.4,48,1.9,1998,12.6,0.56,0.0,0.0,Summer,No Holiday,Yes,2018-06-04 18:00:00,False

# 오후 1시 다시 시작

In [52]:
from helper import load_titanic
df = load_titanic()
small = df[['Name', 'Age', 'Fare', 'Cabin']]
small.groupby('Age')[['Fare']].mean().style.bar(subset='Fare')