In [10]:
import pandas as pd

s = pd.Series([10, 20, 30], index=['a', 'b', 'c'])
print(s.values)
print(s.index)
s * 2
# Dataframe
data = {
    'name': ['Alice', 'Bob', 'Cathy'],
    'age': [25, 30, 35]
}
small = pd.DataFrame(data)
small

[10 20 30]
Index(['a', 'b', 'c'], dtype='str')

    name  age
0  Alice   25
1    Bob   30
2  Cathy   35

In [13]:
from helper import load_titanic
df = load_titanic()
ages = df['Age']
ages.head()

0    22.0
1    38.0
2    26.0
3    35.0
4    35.0
Name: Age, dtype: float64

In [16]:
print(df['Fare'].mean().round(2))
print((df['Fare'] * 1700).head(2))
df[['Age', 'Fare']].mean()

32.2
0     12325.00
1    121181.61
Name: Fare, dtype: float64

Age     29.699118
Fare    32.204208
dtype: float64

In [27]:
# 타이타닉 - Pclass==3 -> Age 평균값과, max 값
# df[df['Pclass'] == 3]['Age'].mean()
# df[df['Pclass'] == 3]['Age'].max()
df[df['Pclass'] == 3]['Age'].agg(['mean', 'max', 'min'])

mean    25.14062
max     74.00000
min      0.42000
Name: Age, dtype: float64

In [45]:
print(df.loc[0, 'Name'])
df.loc[1, 'Ticket']
df.loc[0:2, ['Name', 'Age']]
df.iloc[[0, 5, 10]][['Name']]
mask = df['Fare'] > 100
mask.value_counts()
first_women = (df['Sex'] == 'female') & (df['Pclass'] == 1)
first_women.value_counts()
#  Pclass != 1 이면서, Fare 40 달러 이상 이면서, 남자 승객 갯수
((df['Pclass'] != 1) 
 & (df['Fare'] >= 40) 
 & (df['Sex'] == 'male')).value_counts()

Braund, Mr. Owen Harris

False    870
True      21
Name: count, dtype: int64

In [51]:
df['Pclass'].isin([2, 3]).value_counts()
df['Age'].between(20, 30).value_counts()
df.query('Fare > 100 and Sex == "male"')[['Name', 'Fare']].head()

                               Name      Fare
27   Fortune, Mr. Charles Alexander  263.0000
118        Baxter, Mr. Quigg Edmond  247.5208
305  Allison, Master. Hudson Trevor  151.5500
332       Graham, Mr. George Edward  153.4625
373             Ringhini, Mr. Sante  135.6333

In [54]:
df[df['Name'].str.contains('Anderson')]['Name']

460             Anderson, Mr. Harry
515    Walker, Mr. William Anderson
682     Olsvigen, Mr. Thor Anderson
Name: Name, dtype: str